import { z } from 'zod';

export const weatherSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  timezone: z.string(),
  timezone_abbreviation: z.string(),
  elevation: z.number(),
  current_units: z.object({
    time: z.string(),
    temperature_2m: z.string(),
    relative_humidity_2m: z.string(),
    apparent_temperature: z.string(),
    is_day: z.string(),
    precipitation: z.string(),
    rain: z.string(),
    showers: z.string(),
    snowfall: z.string(),
    weather_code: z.string(),
    cloud_cover: z.string(),
    wind_speed_10m: z.string(),
    wind_direction_10m: z.string(),
    wind_gusts_10m: z.string(),
  }),
  current: z.object({
    time: z.string(),
    temperature_2m: z.number(),
    relative_humidity_2m: z.number(),
    apparent_temperature: z.number(),
    is_day: z.number(),
    precipitation: z.number(),
    rain: z.number(),
    showers: z.number(),
    snowfall: z.number(),
    weather_code: z.number(),
    cloud_cover: z.number(),
    wind_speed_10m: z.number(),
    wind_direction_10m: z.number(),
    wind_gusts_10m: z.number(),
  }),
  hourly_units: z.object({
    time: z.string(),
    temperature_2m: z.string(),
    weather_code: z.string(),
    precipitation_probability: z.string(),
  }),
  hourly: z.object({
    time: z.array(z.string()),
    temperature_2m: z.array(z.number()),
    weather_code: z.array(z.number()),
    precipitation_probability: z.array(z.number()),
  }),
  daily_units: z.object({
    time: z.string(),
    weather_code: z.string(),
    temperature_2m_max: z.string(),
    temperature_2m_min: z.string(),
    precipitation_sum: z.string(),
    precipitation_probability_max: z.string(),
  }),
  daily: z.object({
    time: z.array(z.string()),
    weather_code: z.array(z.number()),
    temperature_2m_max: z.array(z.number()),
    temperature_2m_min: z.array(z.number()),
    precipitation_sum: z.array(z.number()),
    precipitation_probability_max: z.array(z.number()),
  }),
});

export type WeatherResponse = z.infer<typeof weatherSchema>;
