#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
MAGENTA='\033[1;35m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

if pnpm test --run; then
  printf "${GREEN}✅ Awesome! Your tests passed with flying colors! Smooth sailing ahead! 🌈🏆${NC}\n"
else
  printf "${MAGENTA}⛔️ Oops! Your tests encountered a few hurdles. Time to don the debugging cape! 🦸‍♀️🔍${NC}\n"
  printf "${YELLOW}💡 Pro Tip: Grab some ☕, dive into the code sea, and let's troubleshoot like pros! 🌊🧩${NC}\n"
  exit 1
fi
